const NAV = "/assets/nav";

export const navAssets = {
  settings: `${NAV}/icons/settings.svg`,
  backArrow: `${NAV}/icons/back-arrow.svg`,
  backButton: `${NAV}/icons/back-button.svg`,
  bgEllipse: `${NAV}/images/bg-ellipse.svg`,
  locationPulse: `${NAV}/icons/location-pulse.svg`,
  loading: `${NAV}/images/loading.svg`,
  locationIcon: `${NAV}/icons/location.svg`,
  locationPhoto: `${NAV}/images/location.png`,
  train: `${NAV}/icons/transfer.svg`,
  exit: `${NAV}/icons/exit.svg`,
  elevator: `${NAV}/icons/elevator.svg`,
  restroom: `${NAV}/icons/restroom.svg`,
  voiceWaitingCenter: `${NAV}/images/voice%20waiting%20center.svg`,
  voiceWaitingRadar: `${NAV}/images/voice%20waiting%20radar.svg`,
  voiceCenter: `${NAV}/images/voice%20center.svg`,
  voiceRadar: `${NAV}/images/voice%20radar.svg`,
  voiceRing: `${NAV}/images/voice%20ring.svg`,
  loading2Center: `${NAV}/images/loading-2-center.svg`,
  loading2Radar1: `${NAV}/images/loading-2-radar-1.svg`,
  loading2Radar2: `${NAV}/images/loading-2-radar-2.svg`,
  loading2RadarMini: `${NAV}/images/loading-2-radar-mini.svg`,
  loading2Ring1: `${NAV}/images/loading-2-ring-1.svg`,
  loading2Ring2: `${NAV}/images/loading-2-ring-2.svg`,
  transferGuide1: `${NAV}/images/transfer-guide-1-bg.jpg`,
  transferGuide2: `${NAV}/images/transfer-guide-2-bg.png`,
  transferGuideFinish: `${NAV}/images/15_transfer_guide_finish.png`,
  transferGuideFinishCharacter: "/assets/tutorial-map/practice-complete-character.png",
  setupAvatar: `${NAV}/images/setup-avatar.svg`,
  setupPencil: `${NAV}/icons/setup-pencil.svg`,
  setupChangeAvatar: `${NAV}/icons/setup-change%20avatar.svg`,
  setupChangePersonality: `${NAV}/icons/setup-change%20personality.svg`,
  setupChangeName: `${NAV}/icons/setup-change-name.svg`,
  setupArrow: `${NAV}/icons/setup-arrow.svg`,
  setupText: `${NAV}/icons/setup-text.svg`,
  setupVolume: `${NAV}/icons/setup-volume.svg`,
  setupVolumeSmall: `${NAV}/icons/setup-volume-small.svg`,
  setupVolumeBig: `${NAV}/icons/setup-volume-big.svg`,
  wifi: `${NAV}/icons/wifi.svg`,
  signal: `${NAV}/icons/signal.svg`,
  battery: `${NAV}/icons/battery.svg`,
} as const;
